#III - Configuracaoes - 12 factor apps
#Tudo que usa o valor @ esta referenciando o arquivo pom.xml
project:
  name: 'ads4'
  version: '0.0.1-SNAPSHOT'
  description: 'Demo project for Spring Boot'
info:
  build:
    artifact: "ads4"
    name: "ads4 xpto"
    description: 'Demo project for Spring Boot'
    version: '0.0.1-SNAPSHOT'
application:
  title: ${project.name}
  version: ${project.version}

spring:
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLE:always}
  banner:
    charset: ${SPRING_BANNER_CHARSET:UTF-8}
    location: ${SPRING_BANNER_LOCATION:classpath:/banner.txt}

  #Database sempre que adicionar um banco vc precisa addionar a dependencia no pom.xml
  datasource:
    driver-class-name: ${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none #create-drop
    show-sql: true #Opcao para apresentar a execucao de SQL no projeto.
    open-in-view: false
    database: postgresql
    generate-ddl: true #Cria DDDL (Crias a instrucoes de criacao/alteracao de tabela)
    properties:
      hibernate:
        format_sql: false


#Logging
logging:
  level:
    com.provawebservice.provan1: debug
    org.springframework.web: info
    org:
      hibernate:
        orm.jdbc.bind: trace
        SQL: info
        type: trace
        #type:
        #  descriptor.sql: trace